# 1. データベースへの接続設定
# データベース名が「my_pet_diary_db」であることを確認してください
spring.datasource.url=jdbc:mysql://localhost:3306/my_pet_diary_db?useSSL=false&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=

# 2. JPA/Hibernateの設定
# SQL文をコンソールに表示して、動いているか確認しやすくします
spring.jpa.show-sql=true
# テーブルは自分たちで作成済みなので、自動生成はオフにします
spring.jpa.hibernate.ddl-auto=update

# 1ファイルあたりの最大サイズ（例: 10MBに設定）
spring.servlet.multipart.max-file-size=10MB

# 1リクエスト（フォーム全体）の最大サイズ（例: 10MBに設定）
spring.servlet.multipart.max-request-size=10MB